name: Weekly Data Update

on:
  schedule:
    - cron: "0 10 * * 1"  # Runs every Monday at 5:00 A.M. ET (10:00 A.M. UTC)
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests pandas

      - name: Run Data Update Script
        id: update_script
        run: python data_update.py

      - name: Read Update Status (Base64)
        id: read_status
        run: |
          b64_content=$(base64 -w 0 update_status.txt)
          echo "status_b64=$b64_content" >> $GITHUB_OUTPUT

      - name: Decode Status for Email
        id: decode_status
        run: |
          echo "${{ steps.read_status.outputs.status_b64 }}" | base64 -d > status_decoded.txt
          echo "status<<EOF" >> $GITHUB_OUTPUT
          cat status_decoded.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send Email Notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "GitHub Data Update Report"
          body: |
            Weekly data update has completed.

            ${{ steps.decode_status.outputs.status }}

            View logs: https://github.com/sopatz/USCityPopByCounty/actions
          to: ${{ secrets.TO_EMAIL }}
          from: ${{ secrets.FROM_EMAIL }}
